/*
 * Quote deck for "Finish the Line" — the pop-culture quote board game.
 *
 * Each entry:
 *   category  – used for the category filter and tile colour
 *   before    – the prompt shown to the player (the setup of the quote)
 *   answer    – the canonical completion (shown on reveal)
 *   accept    – array of accepted answers, all lowercased & punctuation-light.
 *               The player's guess is normalised the same way before matching,
 *               so "full of stars" matches "Full of stars!".
 *   source    – where it's from (shown after the round)
 *   points    – how many spaces a correct answer moves you (harder = more)
 */
const QUOTE_DECK = [
  // ---- Movies ----
  {
    category: "Movies",
    before: "Oh my God, it's",
    answer: "full of stars",
    accept: ["full of stars"],
    source: "2001: A Space Odyssey (2010 line)",
    points: 3,
  },
  {
    category: "Movies",
    before: "Here's looking at you,",
    answer: "kid",
    accept: ["kid"],
    source: "Casablanca",
    points: 1,
  },
  {
    category: "Movies",
    before: "May the Force be",
    answer: "with you",
    accept: ["with you"],
    source: "Star Wars",
    points: 1,
  },
  {
    category: "Movies",
    before: "I'm going to make him an offer he",
    answer: "can't refuse",
    accept: ["can't refuse", "cannot refuse"],
    source: "The Godfather",
    points: 2,
  },
  {
    category: "Movies",
    before: "You're gonna need a bigger",
    answer: "boat",
    accept: ["boat"],
    source: "Jaws",
    points: 1,
  },
  {
    category: "Movies",
    before: "Life is like a box of",
    answer: "chocolates",
    accept: ["chocolates", "chocolate"],
    source: "Forrest Gump",
    points: 1,
  },
  {
    category: "Movies",
    before: "Frankly, my dear, I don't give a",
    answer: "damn",
    accept: ["damn"],
    source: "Gone with the Wind",
    points: 2,
  },
  {
    category: "Movies",
    before: "Say hello to my little",
    answer: "friend",
    accept: ["friend"],
    source: "Scarface",
    points: 1,
  },
  {
    category: "Movies",
    before: "Why so",
    answer: "serious?",
    accept: ["serious"],
    source: "The Dark Knight",
    points: 2,
  },
  {
    category: "Movies",
    before: "You had me at",
    answer: "hello",
    accept: ["hello"],
    source: "Jerry Maguire",
    points: 2,
  },
  {
    category: "Movies",
    before: "To infinity and",
    answer: "beyond",
    accept: ["beyond"],
    source: "Toy Story",
    points: 1,
  },
  {
    category: "Movies",
    before: "I'll be",
    answer: "back",
    accept: ["back"],
    source: "The Terminator",
    points: 1,
  },
  {
    category: "Movies",
    before: "There's no place like",
    answer: "home",
    accept: ["home"],
    source: "The Wizard of Oz",
    points: 1,
  },
  {
    category: "Movies",
    before: "Just keep",
    answer: "swimming",
    accept: ["swimming"],
    source: "Finding Nemo",
    points: 1,
  },

  // ---- TV ----
  {
    category: "TV",
    before: "How you",
    answer: "doin'?",
    accept: ["doin", "doing", "doin'"],
    source: "Friends (Joey)",
    points: 2,
  },
  {
    category: "TV",
    before: "Winter is",
    answer: "coming",
    accept: ["coming"],
    source: "Game of Thrones",
    points: 1,
  },
  {
    category: "TV",
    before: "I am the one who",
    answer: "knocks",
    accept: ["knocks"],
    source: "Breaking Bad",
    points: 2,
  },
  {
    category: "TV",
    before: "That's what",
    answer: "she said",
    accept: ["she said"],
    source: "The Office (Michael Scott)",
    points: 2,
  },
  {
    category: "TV",
    before: "Legen — wait for it —",
    answer: "dary",
    accept: ["dary", "legendary"],
    source: "How I Met Your Mother (Barney)",
    points: 2,
  },
  {
    category: "TV",
    before: "Live long and",
    answer: "prosper",
    accept: ["prosper"],
    source: "Star Trek",
    points: 1,
  },
  {
    category: "TV",
    before: "Yada yada",
    answer: "yada",
    accept: ["yada"],
    source: "Seinfeld",
    points: 2,
  },

  // ---- Music ----
  {
    category: "Music",
    before: "Is this the real life? Is this just",
    answer: "fantasy?",
    accept: ["fantasy"],
    source: "Queen — Bohemian Rhapsody",
    points: 2,
  },
  {
    category: "Music",
    before: "'Cause baby, you're a",
    answer: "firework",
    accept: ["firework", "fire work"],
    source: "Katy Perry — Firework",
    points: 2,
  },
  {
    category: "Music",
    before: "We don't need no",
    answer: "education",
    accept: ["education"],
    source: "Pink Floyd — Another Brick in the Wall",
    points: 2,
  },
  {
    category: "Music",
    before: "I want it",
    answer: "that way",
    accept: ["that way"],
    source: "Backstreet Boys — I Want It That Way",
    points: 2,
  },
  {
    category: "Music",
    before: "Hello from the",
    answer: "other side",
    accept: ["other side", "otherside"],
    source: "Adele — Hello",
    points: 2,
  },
  {
    category: "Music",
    before: "Sweet dreams are made of",
    answer: "this",
    accept: ["this", "these"],
    source: "Eurythmics — Sweet Dreams",
    points: 2,
  },
  {
    category: "Music",
    before: "Never gonna give you",
    answer: "up",
    accept: ["up"],
    source: "Rick Astley — Never Gonna Give You Up",
    points: 1,
  },

  // ---- Internet / Memes ----
  {
    category: "Internet",
    before: "All your base are belong to",
    answer: "us",
    accept: ["us"],
    source: "Zero Wing (meme)",
    points: 3,
  },
  {
    category: "Internet",
    before: "One does not simply walk into",
    answer: "Mordor",
    accept: ["mordor"],
    source: "LOTR / meme",
    points: 2,
  },
  {
    category: "Internet",
    before: "It's over 9",
    answer: "000!",
    accept: ["000", "9000", "thousand"],
    source: "Dragon Ball Z (meme)",
    points: 2,
  },
  {
    category: "Internet",
    before: "But that's none of my",
    answer: "business",
    accept: ["business"],
    source: "Kermit / meme",
    points: 2,
  },
  {
    category: "Internet",
    before: "I can haz",
    answer: "cheezburger?",
    accept: ["cheezburger", "cheeseburger", "cheezburger?"],
    source: "LOLcats",
    points: 2,
  },

  // ---- Games ----
  {
    category: "Games",
    before: "The cake is a",
    answer: "lie",
    accept: ["lie"],
    source: "Portal",
    points: 2,
  },
  {
    category: "Games",
    before: "It's dangerous to go alone! Take",
    answer: "this",
    accept: ["this", "this."],
    source: "The Legend of Zelda",
    points: 2,
  },
  {
    category: "Games",
    before: "War. War never",
    answer: "changes",
    accept: ["changes"],
    source: "Fallout",
    points: 2,
  },
  {
    category: "Games",
    before: "A man chooses, a slave",
    answer: "obeys",
    accept: ["obeys"],
    source: "BioShock",
    points: 3,
  },
  {
    category: "Games",
    before: "Do a",
    answer: "barrel roll!",
    accept: ["barrel roll", "barrel roll!"],
    source: "Star Fox 64",
    points: 2,
  },

  // ---- Movies (expansion) ----
  {
    category: "Movies",
    before: "I see dead",
    answer: "people",
    accept: ["people"],
    source: "The Sixth Sense",
    points: 2,
  },
  {
    category: "Movies",
    before: "You can't handle the",
    answer: "truth!",
    accept: ["truth"],
    source: "A Few Good Men",
    points: 2,
  },
  {
    category: "Movies",
    before: "Houston, we have a",
    answer: "problem",
    accept: ["problem"],
    source: "Apollo 13",
    points: 1,
  },
  {
    category: "Movies",
    before: "Elementary, my dear",
    answer: "Watson",
    accept: ["watson"],
    source: "Sherlock Holmes",
    points: 2,
  },
  {
    category: "Movies",
    before: "I feel the need — the need for",
    answer: "speed",
    accept: ["speed", "for speed"],
    source: "Top Gun",
    points: 2,
  },
  {
    category: "Movies",
    before: "Nobody puts Baby in a",
    answer: "corner",
    accept: ["corner"],
    source: "Dirty Dancing",
    points: 2,
  },
  {
    category: "Movies",
    before: "They may take our lives, but they'll never take our",
    answer: "freedom!",
    accept: ["freedom"],
    source: "Braveheart",
    points: 3,
  },
  {
    category: "Movies",
    before: "Keep your friends close, but your enemies",
    answer: "closer",
    accept: ["closer", "even closer"],
    source: "The Godfather Part II",
    points: 2,
  },
  {
    category: "Movies",
    before: "You talkin' to",
    answer: "me?",
    accept: ["me"],
    source: "Taxi Driver",
    points: 2,
  },
  {
    category: "Movies",
    before: "Hasta la vista,",
    answer: "baby",
    accept: ["baby"],
    source: "Terminator 2: Judgment Day",
    points: 2,
  },
  {
    category: "Movies",
    before: "Roads? Where we're going, we don't need",
    answer: "roads",
    accept: ["roads"],
    source: "Back to the Future",
    points: 2,
  },
  {
    category: "Movies",
    before: "With great power comes great",
    answer: "responsibility",
    accept: ["responsibility"],
    source: "Spider-Man",
    points: 1,
  },
  {
    category: "Movies",
    before: "No, I am your",
    answer: "father",
    accept: ["father"],
    source: "The Empire Strikes Back",
    points: 1,
  },
  {
    category: "Movies",
    before: "Do. Or do not. There is no",
    answer: "try",
    accept: ["try"],
    source: "The Empire Strikes Back (Yoda)",
    points: 2,
  },
  {
    category: "Movies",
    before: "Toto, I've a feeling we're not in Kansas",
    answer: "anymore",
    accept: ["anymore", "any more"],
    source: "The Wizard of Oz",
    points: 2,
  },
  {
    category: "Movies",
    before: "You shall not",
    answer: "pass!",
    accept: ["pass"],
    source: "The Lord of the Rings (Gandalf)",
    points: 2,
  },
  {
    category: "Movies",
    before: "Wax on, wax",
    answer: "off",
    accept: ["off"],
    source: "The Karate Kid",
    points: 2,
  },
  {
    category: "Movies",
    before: "E.T. phone",
    answer: "home",
    accept: ["home"],
    source: "E.T. the Extra-Terrestrial",
    points: 1,
  },
  {
    category: "Movies",
    before: "I'm the king of the",
    answer: "world!",
    accept: ["world"],
    source: "Titanic",
    points: 2,
  },
  {
    category: "Movies",
    before: "Show me the",
    answer: "money!",
    accept: ["money"],
    source: "Jerry Maguire",
    points: 2,
  },
  {
    category: "Movies",
    before: "Round up the usual",
    answer: "suspects",
    accept: ["suspects"],
    source: "Casablanca",
    points: 2,
  },
  {
    category: "Movies",
    before: "Carpe diem. Seize the",
    answer: "day",
    accept: ["day", "day boys", "day, boys"],
    source: "Dead Poets Society",
    points: 2,
  },
  {
    category: "Movies",
    before: "The first rule of Fight Club is: you do not talk about",
    answer: "Fight Club",
    accept: ["fight club"],
    source: "Fight Club",
    points: 2,
  },
  {
    category: "Movies",
    before: "Life finds a",
    answer: "way",
    accept: ["way"],
    source: "Jurassic Park",
    points: 2,
  },

  // ---- TV (expansion) ----
  {
    category: "TV",
    before: "Have you tried turning it off and on",
    answer: "again?",
    accept: ["again"],
    source: "The IT Crowd",
    points: 2,
  },
  {
    category: "TV",
    before: "Suit",
    answer: "up!",
    accept: ["up"],
    source: "How I Met Your Mother (Barney)",
    points: 2,
  },
  {
    category: "TV",
    before: "The truth is out",
    answer: "there",
    accept: ["there"],
    source: "The X-Files",
    points: 2,
  },
  {
    category: "TV",
    before: "Resistance is",
    answer: "futile",
    accept: ["futile"],
    source: "Star Trek: The Next Generation (Borg)",
    points: 2,
  },
  {
    category: "TV",
    before: "Space: the final",
    answer: "frontier",
    accept: ["frontier"],
    source: "Star Trek",
    points: 1,
  },
  {
    category: "TV",
    before: "Make it",
    answer: "so",
    accept: ["so"],
    source: "Star Trek: TNG (Picard)",
    points: 2,
  },
  {
    category: "TV",
    before: "I've made a huge",
    answer: "mistake",
    accept: ["mistake"],
    source: "Arrested Development",
    points: 3,
  },
  {
    category: "TV",
    before: "No soup for",
    answer: "you!",
    accept: ["you"],
    source: "Seinfeld (Soup Nazi)",
    points: 2,
  },
  {
    category: "TV",
    before: "Survey",
    answer: "says!",
    accept: ["says"],
    source: "Family Feud",
    points: 2,
  },
  {
    category: "TV",
    before: "Book 'em,",
    answer: "Danno",
    accept: ["danno"],
    source: "Hawaii Five-O",
    points: 3,
  },
  {
    category: "TV",
    before: "And that's the way it",
    answer: "is",
    accept: ["is"],
    source: "CBS Evening News (Walter Cronkite)",
    points: 3,
  },
  {
    category: "TV",
    before: "You are the weakest link,",
    answer: "goodbye",
    accept: ["goodbye", "good bye"],
    source: "The Weakest Link",
    points: 2,
  },
  {
    category: "TV",
    before: "Danger, Will",
    answer: "Robinson!",
    accept: ["robinson"],
    source: "Lost in Space",
    points: 3,
  },
  {
    category: "TV",
    before: "Whatchu talkin' 'bout,",
    answer: "Willis?",
    accept: ["willis"],
    source: "Diff'rent Strokes",
    points: 3,
  },
  {
    category: "TV",
    before: "Marcia, Marcia,",
    answer: "Marcia!",
    accept: ["marcia"],
    source: "The Brady Bunch",
    points: 3,
  },
  {
    category: "TV",
    before: "Clear eyes, full hearts,",
    answer: "can't lose",
    accept: ["can't lose", "cant lose"],
    source: "Friday Night Lights",
    points: 3,
  },
  {
    category: "TV",
    before: "Say my",
    answer: "name",
    accept: ["name"],
    source: "Breaking Bad",
    points: 2,
  },

  // ---- Music (expansion) ----
  {
    category: "Music",
    before: "Don't stop",
    answer: "believin'",
    accept: ["believin", "believing"],
    source: "Journey — Don't Stop Believin'",
    points: 1,
  },
  {
    category: "Music",
    before: "We will, we will",
    answer: "rock you",
    accept: ["rock you"],
    source: "Queen — We Will Rock You",
    points: 1,
  },
  {
    category: "Music",
    before: "And I will always love",
    answer: "you",
    accept: ["you"],
    source: "Whitney Houston — I Will Always Love You",
    points: 1,
  },
  {
    category: "Music",
    before: "Girls just wanna have",
    answer: "fun",
    accept: ["fun"],
    source: "Cyndi Lauper — Girls Just Want to Have Fun",
    points: 1,
  },
  {
    category: "Music",
    before: "Billie Jean is not my",
    answer: "lover",
    accept: ["lover"],
    source: "Michael Jackson — Billie Jean",
    points: 2,
  },
  {
    category: "Music",
    before: "Take on",
    answer: "me",
    accept: ["me"],
    source: "a-ha — Take On Me",
    points: 2,
  },
  {
    category: "Music",
    before: "Should I stay or should I",
    answer: "go",
    accept: ["go", "go now"],
    source: "The Clash — Should I Stay or Should I Go",
    points: 2,
  },
  {
    category: "Music",
    before: "Another one bites the",
    answer: "dust",
    accept: ["dust"],
    source: "Queen — Another One Bites the Dust",
    points: 1,
  },
  {
    category: "Music",
    before: "I'm on the highway to",
    answer: "hell",
    accept: ["hell"],
    source: "AC/DC — Highway to Hell",
    points: 2,
  },
  {
    category: "Music",
    before: "Whoa, we're halfway there — livin' on a",
    answer: "prayer",
    accept: ["prayer"],
    source: "Bon Jovi — Livin' on a Prayer",
    points: 2,
  },
  {
    category: "Music",
    before: "Every breath you",
    answer: "take",
    accept: ["take"],
    source: "The Police — Every Breath You Take",
    points: 2,
  },
  {
    category: "Music",
    before: "Players gonna play — I just shake it",
    answer: "off",
    accept: ["off"],
    source: "Taylor Swift — Shake It Off",
    points: 1,
  },
  {
    category: "Music",
    before: "Oops!... I did it",
    answer: "again",
    accept: ["again"],
    source: "Britney Spears — Oops!... I Did It Again",
    points: 1,
  },
  {
    category: "Music",
    before: "Hit me baby one more",
    answer: "time",
    accept: ["time"],
    source: "Britney Spears — ...Baby One More Time",
    points: 2,
  },
  {
    category: "Music",
    before: "Clap along if you feel like a room without a",
    answer: "roof",
    accept: ["roof"],
    source: "Pharrell Williams — Happy",
    points: 3,
  },
  {
    category: "Music",
    before: "Somebody once told me the world is gonna roll",
    answer: "me",
    accept: ["me"],
    source: "Smash Mouth — All Star",
    points: 3,
  },
  {
    category: "Music",
    before: "I gotta feeling that tonight's gonna be a good",
    answer: "night",
    accept: ["night"],
    source: "The Black Eyed Peas — I Gotta Feeling",
    points: 2,
  },
  {
    category: "Music",
    before: "You may say I'm a dreamer, but I'm not the only",
    answer: "one",
    accept: ["one"],
    source: "John Lennon — Imagine",
    points: 2,
  },

  // ---- Internet / Memes (expansion) ----
  {
    category: "Internet",
    before: "This is",
    answer: "Sparta!",
    accept: ["sparta"],
    source: "300 (meme)",
    points: 2,
  },
  {
    category: "Internet",
    before: "Ain't nobody got time for",
    answer: "that",
    accept: ["that"],
    source: "viral news clip (meme)",
    points: 2,
  },
  {
    category: "Internet",
    before: "Shut up and take my",
    answer: "money!",
    accept: ["money"],
    source: "Futurama (meme)",
    points: 2,
  },
  {
    category: "Internet",
    before: "Release the",
    answer: "Kraken!",
    accept: ["kraken"],
    source: "Clash of the Titans (meme)",
    points: 2,
  },
  {
    category: "Internet",
    before: "Keep calm and carry",
    answer: "on",
    accept: ["on"],
    source: "wartime poster (meme)",
    points: 1,
  },
  {
    category: "Internet",
    before: "Well, that escalated",
    answer: "quickly",
    accept: ["quickly"],
    source: "Anchorman (meme)",
    points: 2,
  },
  {
    category: "Internet",
    before: "The floor is",
    answer: "lava",
    accept: ["lava"],
    source: "childhood game (meme)",
    points: 2,
  },
  {
    category: "Internet",
    before: "Pics or it didn't",
    answer: "happen",
    accept: ["happen"],
    source: "internet saying",
    points: 2,
  },
  {
    category: "Internet",
    before: "Do you want ants? Because that's how you get",
    answer: "ants",
    accept: ["ants"],
    source: "Archer (meme)",
    points: 3,
  },
  {
    category: "Internet",
    before: "Do you even",
    answer: "lift?",
    accept: ["lift"],
    source: "gym meme",
    points: 2,
  },
  {
    category: "Internet",
    before: "Leeroy",
    answer: "Jenkins!",
    accept: ["jenkins"],
    source: "World of Warcraft (meme)",
    points: 3,
  },
  {
    category: "Internet",
    before: "Por que no los",
    answer: "dos?",
    accept: ["dos", "two", "both"],
    source: "Old El Paso ad — \"why not both?\" (meme)",
    points: 3,
  },

  // ---- Games (expansion) ----
  {
    category: "Games",
    before: "Finish",
    answer: "him!",
    accept: ["him"],
    source: "Mortal Kombat",
    points: 2,
  },
  {
    category: "Games",
    before: "Thank you Mario! But our princess is in another",
    answer: "castle!",
    accept: ["castle"],
    source: "Super Mario Bros.",
    points: 3,
  },
  {
    category: "Games",
    before: "It's-a me,",
    answer: "Mario!",
    accept: ["mario"],
    source: "Super Mario 64",
    points: 1,
  },
  {
    category: "Games",
    before: "Get over",
    answer: "here!",
    accept: ["here"],
    source: "Mortal Kombat (Scorpion)",
    points: 2,
  },
  {
    category: "Games",
    before: "Stay a while and",
    answer: "listen",
    accept: ["listen"],
    source: "Diablo (Deckard Cain)",
    points: 3,
  },
  {
    category: "Games",
    before: "You must construct additional",
    answer: "pylons",
    accept: ["pylons"],
    source: "StarCraft",
    points: 3,
  },
  {
    category: "Games",
    before: "Nothing is true; everything is",
    answer: "permitted",
    accept: ["permitted"],
    source: "Assassin's Creed",
    points: 3,
  },
  {
    category: "Games",
    before: "Praise the",
    answer: "sun!",
    accept: ["sun"],
    source: "Dark Souls",
    points: 3,
  },
  {
    category: "Games",
    before: "Fus Ro",
    answer: "Dah!",
    accept: ["dah"],
    source: "The Elder Scrolls V: Skyrim",
    points: 3,
  },
  {
    category: "Games",
    before: "I used to be an adventurer like you, then I took an arrow to the",
    answer: "knee",
    accept: ["knee"],
    source: "The Elder Scrolls V: Skyrim",
    points: 3,
  },

  // ---- Movies (batch 3) ----
  {
    category: "Movies",
    before: "Go ahead, make my",
    answer: "day",
    accept: ["day"],
    source: "Sudden Impact (Dirty Harry)",
    points: 2,
  },
  {
    category: "Movies",
    before: "I'll have what she's",
    answer: "having",
    accept: ["having"],
    source: "When Harry Met Sally",
    points: 2,
  },
  {
    category: "Movies",
    before: "There's no crying in",
    answer: "baseball!",
    accept: ["baseball"],
    source: "A League of Their Own",
    points: 2,
  },
  {
    category: "Movies",
    before: "You're a wizard,",
    answer: "Harry",
    accept: ["harry"],
    source: "Harry Potter and the Philosopher's Stone",
    points: 1,
  },
  {
    category: "Movies",
    before: "Hakuna",
    answer: "matata",
    accept: ["matata"],
    source: "The Lion King",
    points: 1,
  },
  {
    category: "Movies",
    before: "I volunteer as",
    answer: "tribute!",
    accept: ["tribute"],
    source: "The Hunger Games",
    points: 2,
  },
  {
    category: "Movies",
    before: "May the odds be ever in your",
    answer: "favor",
    accept: ["favor", "favour"],
    source: "The Hunger Games",
    points: 2,
  },
  {
    category: "Movies",
    before: "Greed, for lack of a better word, is",
    answer: "good",
    accept: ["good"],
    source: "Wall Street",
    points: 2,
  },
  {
    category: "Movies",
    before: "Hello. My name is Inigo Montoya. You killed my father. Prepare to",
    answer: "die",
    accept: ["die"],
    source: "The Princess Bride",
    points: 3,
  },
  {
    category: "Movies",
    before: "As you",
    answer: "wish",
    accept: ["wish"],
    source: "The Princess Bride",
    points: 2,
  },
  {
    category: "Movies",
    before: "Surely you can't be serious. I am serious. And don't call me",
    answer: "Shirley",
    accept: ["shirley"],
    source: "Airplane!",
    points: 3,
  },
  {
    category: "Movies",
    before: "I love the smell of napalm in the",
    answer: "morning",
    accept: ["morning"],
    source: "Apocalypse Now",
    points: 3,
  },
  {
    category: "Movies",
    before: "Well, nobody's",
    answer: "perfect",
    accept: ["perfect"],
    source: "Some Like It Hot",
    points: 3,
  },
  {
    category: "Movies",
    before: "They call it a Royale with",
    answer: "cheese",
    accept: ["cheese"],
    source: "Pulp Fiction",
    points: 3,
  },
  {
    category: "Movies",
    before: "I drink your",
    answer: "milkshake!",
    accept: ["milkshake", "milk shake"],
    source: "There Will Be Blood",
    points: 3,
  },
  {
    category: "Movies",
    before: "You is kind. You is smart. You is",
    answer: "important",
    accept: ["important"],
    source: "The Help",
    points: 3,
  },
  {
    category: "Movies",
    before: "I wish I knew how to quit",
    answer: "you",
    accept: ["you"],
    source: "Brokeback Mountain",
    points: 3,
  },
  {
    category: "Movies",
    before: "Bond. James",
    answer: "Bond",
    accept: ["bond"],
    source: "James Bond films",
    points: 1,
  },
  {
    category: "Movies",
    before: "A martini. Shaken, not",
    answer: "stirred",
    accept: ["stirred"],
    source: "James Bond films",
    points: 1,
  },
  {
    category: "Movies",
    before: "You keep using that word. I do not think it means what you think it",
    answer: "means",
    accept: ["means"],
    source: "The Princess Bride",
    points: 3,
  },

  // ---- TV (batch 3) ----
  {
    category: "TV",
    before: "Yabba dabba",
    answer: "doo!",
    accept: ["doo"],
    source: "The Flintstones",
    points: 2,
  },
  {
    category: "TV",
    before: "To the moon,",
    answer: "Alice!",
    accept: ["alice"],
    source: "The Honeymooners",
    points: 3,
  },
  {
    category: "TV",
    before: "Good news,",
    answer: "everyone!",
    accept: ["everyone", "everybody"],
    source: "Futurama (Professor Farnsworth)",
    points: 3,
  },
  {
    category: "TV",
    before: "Dental plan! Lisa needs",
    answer: "braces",
    accept: ["braces"],
    source: "The Simpsons",
    points: 3,
  },
  {
    category: "TV",
    before: "Eat my",
    answer: "shorts!",
    accept: ["shorts"],
    source: "The Simpsons (Bart)",
    points: 2,
  },
  {
    category: "TV",
    before: "Cowabunga,",
    answer: "dude!",
    accept: ["dude"],
    source: "Teenage Mutant Ninja Turtles",
    points: 3,
  },
  {
    category: "TV",
    before: "The tribe has",
    answer: "spoken",
    accept: ["spoken"],
    source: "Survivor",
    points: 2,
  },
  {
    category: "TV",
    before: "You're",
    answer: "fired!",
    accept: ["fired"],
    source: "The Apprentice",
    points: 2,
  },
  {
    category: "TV",
    before: "Is that your final",
    answer: "answer?",
    accept: ["answer"],
    source: "Who Wants to Be a Millionaire",
    points: 2,
  },
  {
    category: "TV",
    before: "And I would've gotten away with it too, if it weren't for you meddling",
    answer: "kids!",
    accept: ["kids"],
    source: "Scooby-Doo",
    points: 3,
  },
  {
    category: "TV",
    before: "Treat yo'",
    answer: "self!",
    accept: ["self"],
    source: "Parks and Recreation",
    points: 3,
  },
  {
    category: "TV",
    before: "Remember, phrase your response in the form of a",
    answer: "question",
    accept: ["question"],
    source: "Jeopardy!",
    points: 2,
  },

  // ---- Music (batch 3) ----
  {
    category: "Music",
    before: "I can't get no",
    answer: "satisfaction",
    accept: ["satisfaction"],
    source: "The Rolling Stones — (I Can't Get No) Satisfaction",
    points: 2,
  },
  {
    category: "Music",
    before: "Here we are now,",
    answer: "entertain us",
    accept: ["entertain us"],
    source: "Nirvana — Smells Like Teen Spirit",
    points: 3,
  },
  {
    category: "Music",
    before: "So no one told you life was gonna be this",
    answer: "way",
    accept: ["way"],
    source: "The Rembrandts — I'll Be There for You (Friends theme)",
    points: 3,
  },
  {
    category: "Music",
    before: "'Cause this is",
    answer: "thriller",
    accept: ["thriller"],
    source: "Michael Jackson — Thriller",
    points: 2,
  },
  {
    category: "Music",
    before: "We are the",
    answer: "champions",
    accept: ["champions"],
    source: "Queen — We Are the Champions",
    points: 1,
  },
  {
    category: "Music",
    before: "Bye, bye, Miss American",
    answer: "Pie",
    accept: ["pie"],
    source: "Don McLean — American Pie",
    points: 2,
  },
  {
    category: "Music",
    before: "Started from the bottom now we're",
    answer: "here",
    accept: ["here"],
    source: "Drake — Started From the Bottom",
    points: 2,
  },
  {
    category: "Music",
    before: "I'm a Barbie girl, in a Barbie",
    answer: "world",
    accept: ["world"],
    source: "Aqua — Barbie Girl",
    points: 2,
  },
  {
    category: "Music",
    before: "Hello, is it me you're",
    answer: "looking for?",
    accept: ["looking for"],
    source: "Lionel Richie — Hello",
    points: 3,
  },
  {
    category: "Music",
    before: "Mamma mia, here I go",
    answer: "again",
    accept: ["again"],
    source: "ABBA — Mamma Mia",
    points: 2,
  },
  {
    category: "Music",
    before: "So just beat",
    answer: "it",
    accept: ["it"],
    source: "Michael Jackson — Beat It",
    points: 2,
  },
  {
    category: "Music",
    before: "Big wheels keep on turning — sweet home",
    answer: "Alabama",
    accept: ["alabama"],
    source: "Lynyrd Skynyrd — Sweet Home Alabama",
    points: 2,
  },
  {
    category: "Music",
    before: "And I would walk five hundred miles, and I would walk five hundred",
    answer: "more",
    accept: ["more"],
    source: "The Proclaimers — I'm Gonna Be (500 Miles)",
    points: 3,
  },

  // ---- Internet / Memes (batch 3) ----
  {
    category: "Internet",
    before: "Haters gonna",
    answer: "hate",
    accept: ["hate"],
    source: "internet saying",
    points: 2,
  },
  {
    category: "Internet",
    before: "I'm not saying it was aliens, but it was",
    answer: "aliens",
    accept: ["aliens"],
    source: "Ancient Aliens (meme)",
    points: 3,
  },
  {
    category: "Internet",
    before: "Well yes, but actually",
    answer: "no",
    accept: ["no"],
    source: "meme",
    points: 2,
  },
  {
    category: "Internet",
    before: "Task failed",
    answer: "successfully",
    accept: ["successfully"],
    source: "meme",
    points: 2,
  },
  {
    category: "Internet",
    before: "It's free real",
    answer: "estate",
    accept: ["estate"],
    source: "meme",
    points: 3,
  },
  {
    category: "Internet",
    before: "And my",
    answer: "axe!",
    accept: ["axe", "ax"],
    source: "The Lord of the Rings (meme)",
    points: 2,
  },
  {
    category: "Internet",
    before: "You had one",
    answer: "job",
    accept: ["job"],
    source: "meme",
    points: 2,
  },
  {
    category: "Internet",
    before: "We live in a",
    answer: "society",
    accept: ["society"],
    source: "meme",
    points: 3,
  },
  {
    category: "Internet",
    before: "Understandable, have a great",
    answer: "day",
    accept: ["day"],
    source: "meme",
    points: 3,
  },
  {
    category: "Internet",
    before: "Press F to pay",
    answer: "respects",
    accept: ["respects"],
    source: "Call of Duty: Advanced Warfare (meme)",
    points: 3,
  },

  // ---- Games (batch 3) ----
  {
    category: "Games",
    before: "It's super",
    answer: "effective!",
    accept: ["effective"],
    source: "Pokémon",
    points: 2,
  },
  {
    category: "Games",
    before: "Gotta catch 'em",
    answer: "all!",
    accept: ["all"],
    source: "Pokémon",
    points: 1,
  },
  {
    category: "Games",
    before: "Snake? Snake?!",
    answer: "Snaaake!",
    accept: ["snake", "snaake", "snaaake"],
    source: "Metal Gear Solid",
    points: 3,
  },
  {
    category: "Games",
    before: "All we had to do was follow the damn train,",
    answer: "CJ!",
    accept: ["cj"],
    source: "Grand Theft Auto: San Andreas",
    points: 3,
  },
  {
    category: "Games",
    before: "Hey, you. You're finally",
    answer: "awake",
    accept: ["awake"],
    source: "The Elder Scrolls V: Skyrim",
    points: 3,
  },
  {
    category: "Games",
    before: "The numbers, Mason! What do they",
    answer: "mean?",
    accept: ["mean"],
    source: "Call of Duty: Black Ops",
    points: 3,
  },
  {
    category: "Games",
    before: "You have died of",
    answer: "dysentery",
    accept: ["dysentery"],
    source: "The Oregon Trail",
    points: 3,
  },
  {
    category: "Games",
    before: "Rise and shine, Mr.",
    answer: "Freeman",
    accept: ["freeman"],
    source: "Half-Life 2",
    points: 3,
  },

  // ---- Books ----
  {
    category: "Books",
    before: "It was the best of times, it was the worst of",
    answer: "times",
    accept: ["times"],
    source: "Charles Dickens — A Tale of Two Cities",
    points: 2,
  },
  {
    category: "Books",
    before: "Call me",
    answer: "Ishmael",
    accept: ["ishmael"],
    source: "Herman Melville — Moby-Dick",
    points: 2,
  },
  {
    category: "Books",
    before: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a",
    answer: "wife",
    accept: ["wife"],
    source: "Jane Austen — Pride and Prejudice",
    points: 3,
  },
  {
    category: "Books",
    before: "All animals are equal, but some animals are more equal than",
    answer: "others",
    accept: ["others"],
    source: "George Orwell — Animal Farm",
    points: 3,
  },
  {
    category: "Books",
    before: "Big Brother is watching",
    answer: "you",
    accept: ["you"],
    source: "George Orwell — 1984",
    points: 2,
  },
  {
    category: "Books",
    before: "So it",
    answer: "goes",
    accept: ["goes"],
    source: "Kurt Vonnegut — Slaughterhouse-Five",
    points: 3,
  },
  {
    category: "Books",
    before: "It was a bright cold day in April, and the clocks were striking",
    answer: "thirteen",
    accept: ["thirteen", "13"],
    source: "George Orwell — 1984",
    points: 3,
  },
  {
    category: "Books",
    before: "Not all those who wander are",
    answer: "lost",
    accept: ["lost"],
    source: "J.R.R. Tolkien — The Fellowship of the Ring",
    points: 2,
  },
  {
    category: "Books",
    before: "In a hole in the ground there lived a",
    answer: "hobbit",
    accept: ["hobbit"],
    source: "J.R.R. Tolkien — The Hobbit",
    points: 2,
  },
  {
    category: "Books",
    before: "The answer to the ultimate question of life, the universe, and everything is",
    answer: "42",
    accept: ["42", "forty two", "forty-two"],
    source: "Douglas Adams — The Hitchhiker's Guide to the Galaxy",
    points: 2,
  },
  {
    category: "Books",
    before: "Fear is the mind-",
    answer: "killer",
    accept: ["killer"],
    source: "Frank Herbert — Dune",
    points: 2,
  },
  {
    category: "Books",
    before: "A Lannister always pays his",
    answer: "debts",
    accept: ["debts"],
    source: "George R. R. Martin — A Song of Ice and Fire",
    points: 2,
  },
  {
    category: "Books",
    before: "You're braver than you believe, and stronger than you",
    answer: "seem",
    accept: ["seem"],
    source: "A. A. Milne — Winnie-the-Pooh",
    points: 3,
  },

  // ---- Ads / Slogans ----
  {
    category: "Ads",
    before: "Just do",
    answer: "it",
    accept: ["it"],
    source: "Nike",
    points: 1,
  },
  {
    category: "Ads",
    before: "I'm lovin'",
    answer: "it",
    accept: ["it"],
    source: "McDonald's",
    points: 1,
  },
  {
    category: "Ads",
    before: "Because you're worth",
    answer: "it",
    accept: ["it"],
    source: "L'Oréal",
    points: 2,
  },
  {
    category: "Ads",
    before: "Finger-lickin'",
    answer: "good",
    accept: ["good"],
    source: "KFC",
    points: 2,
  },
  {
    category: "Ads",
    before: "Have it your",
    answer: "way",
    accept: ["way"],
    source: "Burger King",
    points: 2,
  },
  {
    category: "Ads",
    before: "Melts in your mouth, not in your",
    answer: "hands",
    accept: ["hands"],
    source: "M&M's",
    points: 2,
  },
  {
    category: "Ads",
    before: "Snap, crackle,",
    answer: "pop",
    accept: ["pop"],
    source: "Rice Krispies",
    points: 2,
  },
  {
    category: "Ads",
    before: "A diamond is",
    answer: "forever",
    accept: ["forever"],
    source: "De Beers",
    points: 2,
  },
  {
    category: "Ads",
    before: "Think",
    answer: "different",
    accept: ["different"],
    source: "Apple",
    points: 2,
  },
  {
    category: "Ads",
    before: "Red Bull gives you",
    answer: "wings",
    accept: ["wings", "wiiings"],
    source: "Red Bull",
    points: 2,
  },
  {
    category: "Ads",
    before: "Taste the",
    answer: "rainbow",
    accept: ["rainbow"],
    source: "Skittles",
    points: 2,
  },
  {
    category: "Ads",
    before: "Got",
    answer: "milk?",
    accept: ["milk"],
    source: "California Milk Processor Board",
    points: 2,
  },
  {
    category: "Ads",
    before: "They're",
    answer: "grrreat!",
    accept: ["great", "grreat", "grrreat", "grrrreat"],
    source: "Frosted Flakes (Tony the Tiger)",
    points: 2,
  },
  {
    category: "Ads",
    before: "Betcha can't eat just",
    answer: "one",
    accept: ["one"],
    source: "Lay's",
    points: 3,
  },
  {
    category: "Ads",
    before: "Can you hear me",
    answer: "now?",
    accept: ["now"],
    source: "Verizon",
    points: 3,
  },

  // ---- Movies (batch 4) ----
  {
    category: "Movies",
    before: "Mrs. Robinson, you're trying to seduce me. Aren't",
    answer: "you?",
    accept: ["you"],
    source: "The Graduate",
    points: 3,
  },
  {
    category: "Movies",
    before: "Keep the change, ya filthy",
    answer: "animal",
    accept: ["animal"],
    source: "Home Alone",
    points: 2,
  },
  {
    category: "Movies",
    before: "You can't sit with",
    answer: "us!",
    accept: ["us"],
    source: "Mean Girls",
    points: 2,
  },
  {
    category: "Movies",
    before: "On Wednesdays we wear",
    answer: "pink",
    accept: ["pink"],
    source: "Mean Girls",
    points: 2,
  },
  {
    category: "Movies",
    before: "Gretchen, stop trying to make fetch",
    answer: "happen!",
    accept: ["happen"],
    source: "Mean Girls",
    points: 3,
  },
  {
    category: "Movies",
    before: "Why don't you make like a tree and get outta",
    answer: "here",
    accept: ["here"],
    source: "Back to the Future Part II",
    points: 3,
  },
  {
    category: "Movies",
    before: "Hey, I'm walkin'",
    answer: "here!",
    accept: ["here"],
    source: "Midnight Cowboy",
    points: 3,
  },
  {
    category: "Movies",
    before: "Every time a bell rings, an angel gets his",
    answer: "wings",
    accept: ["wings"],
    source: "It's a Wonderful Life",
    points: 2,
  },
  {
    category: "Movies",
    before: "Just when I thought I was out, they pull me back",
    answer: "in",
    accept: ["in"],
    source: "The Godfather Part III",
    points: 3,
  },
  {
    category: "Movies",
    before: "Leave the gun, take the",
    answer: "cannoli",
    accept: ["cannoli"],
    source: "The Godfather",
    points: 2,
  },
  {
    category: "Movies",
    before: "In space, no one can hear you",
    answer: "scream",
    accept: ["scream"],
    source: "Alien (tagline)",
    points: 2,
  },
  {
    category: "Movies",
    before: "Snakes. Why'd it have to be",
    answer: "snakes?",
    accept: ["snakes"],
    source: "Raiders of the Lost Ark",
    points: 3,
  },
  {
    category: "Movies",
    before: "It belongs in a",
    answer: "museum!",
    accept: ["museum"],
    source: "Indiana Jones and the Last Crusade",
    points: 2,
  },
  {
    category: "Movies",
    before: "I have a very particular set of",
    answer: "skills",
    accept: ["skills"],
    source: "Taken",
    points: 2,
  },
  {
    category: "Movies",
    before: "What we've got here is failure to",
    answer: "communicate",
    accept: ["communicate"],
    source: "Cool Hand Luke",
    points: 3,
  },
  {
    category: "Movies",
    before: "Fat, drunk, and stupid is no way to go through",
    answer: "life",
    accept: ["life"],
    source: "Animal House",
    points: 3,
  },
  {
    category: "Movies",
    before: "Chewie, we're",
    answer: "home",
    accept: ["home"],
    source: "Star Wars: The Force Awakens",
    points: 2,
  },
  {
    category: "Movies",
    before: "The greatest trick the Devil ever pulled was convincing the world he didn't",
    answer: "exist",
    accept: ["exist"],
    source: "The Usual Suspects",
    points: 3,
  },
  {
    category: "Movies",
    before: "Some men just want to watch the world",
    answer: "burn",
    accept: ["burn"],
    source: "The Dark Knight",
    points: 2,
  },
  {
    category: "Movies",
    before: "You had my curiosity... but now you have my",
    answer: "attention",
    accept: ["attention"],
    source: "Django Unchained",
    points: 3,
  },

  // ---- TV (batch 4) ----
  {
    category: "TV",
    before: "You got it,",
    answer: "dude!",
    accept: ["dude"],
    source: "Full House (Michelle)",
    points: 3,
  },
  {
    category: "TV",
    before: "Did I do",
    answer: "that?",
    accept: ["that"],
    source: "Family Matters (Urkel)",
    points: 3,
  },
  {
    category: "TV",
    before: "We were on a",
    answer: "break!",
    accept: ["break"],
    source: "Friends (Ross)",
    points: 2,
  },
  {
    category: "TV",
    before: "Smelly cat, smelly cat, what are they feeding",
    answer: "you?",
    accept: ["you"],
    source: "Friends (Phoebe)",
    points: 3,
  },
  {
    category: "TV",
    before: "Sometimes you wanna go where everybody knows your",
    answer: "name",
    accept: ["name"],
    source: "Cheers (theme)",
    points: 2,
  },
  {
    category: "TV",
    before: "Nip it in the",
    answer: "bud",
    accept: ["bud"],
    source: "The Andy Griffith Show (Barney Fife)",
    points: 3,
  },
  {
    category: "TV",
    before: "Just the facts,",
    answer: "ma'am",
    accept: ["maam", "ma am"],
    source: "Dragnet",
    points: 3,
  },
  {
    category: "TV",
    before: "Sock it to",
    answer: "me",
    accept: ["me"],
    source: "Rowan & Martin's Laugh-In",
    points: 3,
  },
  {
    category: "TV",
    before: "Wubba lubba dub",
    answer: "dub!",
    accept: ["dub"],
    source: "Rick and Morty",
    points: 3,
  },
  {
    category: "TV",
    before: "It's a beautiful day in the",
    answer: "neighborhood",
    accept: ["neighborhood", "neighbourhood"],
    source: "Mister Rogers' Neighborhood",
    points: 2,
  },
  {
    category: "TV",
    before: "Won't you be my",
    answer: "neighbor?",
    accept: ["neighbor", "neighbour"],
    source: "Mister Rogers' Neighborhood",
    points: 2,
  },
  {
    category: "TV",
    before: "Two thumbs",
    answer: "up",
    accept: ["up"],
    source: "Siskel & Ebert",
    points: 3,
  },

  // ---- Music (batch 4) ----
  {
    category: "Music",
    before: "I came in like a",
    answer: "wrecking ball",
    accept: ["wrecking ball"],
    source: "Miley Cyrus — Wrecking Ball",
    points: 2,
  },
  {
    category: "Music",
    before: "'Cause all of me loves all of",
    answer: "you",
    accept: ["you"],
    source: "John Legend — All of Me",
    points: 3,
  },
  {
    category: "Music",
    before: "At first I was afraid, I was",
    answer: "petrified",
    accept: ["petrified"],
    source: "Gloria Gaynor — I Will Survive",
    points: 3,
  },
  {
    category: "Music",
    before: "So goodbye yellow brick",
    answer: "road",
    accept: ["road"],
    source: "Elton John — Goodbye Yellow Brick Road",
    points: 2,
  },
  {
    category: "Music",
    before: "Hey Jude, don't make it",
    answer: "bad",
    accept: ["bad"],
    source: "The Beatles — Hey Jude",
    points: 2,
  },
  {
    category: "Music",
    before: "Whisper words of wisdom, let it",
    answer: "be",
    accept: ["be"],
    source: "The Beatles — Let It Be",
    points: 2,
  },
  {
    category: "Music",
    before: "Let it go, let it",
    answer: "go",
    accept: ["go"],
    source: "Frozen — Let It Go",
    points: 1,
  },
  {
    category: "Music",
    before: "We're up all night to get",
    answer: "lucky",
    accept: ["lucky"],
    source: "Daft Punk — Get Lucky",
    points: 2,
  },
  {
    category: "Music",
    before: "'Cause you're a sky full of",
    answer: "stars",
    accept: ["stars"],
    source: "Coldplay — A Sky Full of Stars",
    points: 2,
  },
  {
    category: "Music",
    before: "I'm blue, da ba dee da ba",
    answer: "die",
    accept: ["die", "daa"],
    source: "Eiffel 65 — Blue (Da Ba Dee)",
    points: 3,
  },
  {
    category: "Music",
    before: "Now this is a story all about how my life got flipped, turned upside",
    answer: "down",
    accept: ["down"],
    source: "The Fresh Prince of Bel-Air (theme)",
    points: 2,
  },
  {
    category: "Music",
    before: "In West Philadelphia born and",
    answer: "raised",
    accept: ["raised"],
    source: "The Fresh Prince of Bel-Air (theme)",
    points: 2,
  },
  {
    category: "Music",
    before: "Sweet child o'",
    answer: "mine",
    accept: ["mine"],
    source: "Guns N' Roses — Sweet Child o' Mine",
    points: 2,
  },
  {
    category: "Music",
    before: "Welcome to the",
    answer: "jungle",
    accept: ["jungle"],
    source: "Guns N' Roses — Welcome to the Jungle",
    points: 2,
  },
  {
    category: "Music",
    before: "'Cause we are living in a",
    answer: "material world",
    accept: ["material world"],
    source: "Madonna — Material Girl",
    points: 3,
  },
  {
    category: "Music",
    before: "Touched for the very first time — like a",
    answer: "virgin",
    accept: ["virgin"],
    source: "Madonna — Like a Virgin",
    points: 2,
  },
  {
    category: "Music",
    before: "You spin me right round, baby, right",
    answer: "round",
    accept: ["round"],
    source: "Dead or Alive — You Spin Me Round",
    points: 3,
  },
  {
    category: "Music",
    before: "What is love? Baby, don't hurt",
    answer: "me",
    accept: ["me"],
    source: "Haddaway — What Is Love",
    points: 2,
  },

  // ---- Internet / Memes (batch 4) ----
  {
    category: "Internet",
    before: "Boom goes the",
    answer: "dynamite",
    accept: ["dynamite"],
    source: "viral clip (meme)",
    points: 3,
  },
  {
    category: "Internet",
    before: "Charlie bit my",
    answer: "finger!",
    accept: ["finger"],
    source: "viral video (meme)",
    points: 3,
  },
  {
    category: "Internet",
    before: "Leave Britney",
    answer: "alone!",
    accept: ["alone"],
    source: "viral video (meme)",
    points: 3,
  },
  {
    category: "Internet",
    before: "Damn, Daniel! Back at it again with the white",
    answer: "Vans",
    accept: ["vans"],
    source: "viral video (meme)",
    points: 3,
  },
  {
    category: "Internet",
    before: "It is Wednesday, my",
    answer: "dudes",
    accept: ["dudes"],
    source: "meme",
    points: 3,
  },
  {
    category: "Internet",
    before: "OK",
    answer: "boomer",
    accept: ["boomer"],
    source: "meme",
    points: 2,
  },
  {
    category: "Internet",
    before: "Everything's on fire, but this is",
    answer: "fine",
    accept: ["fine"],
    source: "\"This Is Fine\" dog (meme)",
    points: 3,
  },
  {
    category: "Internet",
    before: "Do it for the",
    answer: "Vine",
    accept: ["vine"],
    source: "Vine (meme)",
    points: 3,
  },
  {
    category: "Internet",
    before: "Op op op op — oppa Gangnam",
    answer: "style!",
    accept: ["style"],
    source: "PSY — Gangnam Style (viral)",
    points: 2,
  },
  {
    category: "Internet",
    before: "And they were",
    answer: "roommates",
    accept: ["roommates", "room mates"],
    source: "Vine (meme)",
    points: 3,
  },

  // ---- Games (batch 4) ----
  {
    category: "Games",
    before: "Kept you",
    answer: "waiting, huh?",
    accept: ["waiting huh", "waiting"],
    source: "Metal Gear Solid V",
    points: 3,
  },
  {
    category: "Games",
    before: "Requiescat in",
    answer: "pace",
    accept: ["pace"],
    source: "Assassin's Creed",
    points: 3,
  },
  {
    category: "Games",
    before: "When life gives you lemons, don't make",
    answer: "lemonade!",
    accept: ["lemonade"],
    source: "Portal 2 (Cave Johnson)",
    points: 3,
  },
  {
    category: "Games",
    before: "The right man in the wrong place can make all the difference in the",
    answer: "world",
    accept: ["world"],
    source: "Half-Life 2 (G-Man)",
    points: 3,
  },
  {
    category: "Games",
    before: "Grass grows, birds fly, sun shines, and brotha, I hurt",
    answer: "people",
    accept: ["people"],
    source: "Team Fortress 2 (Heavy)",
    points: 3,
  },
  {
    category: "Games",
    before: "Reticulating",
    answer: "splines",
    accept: ["splines"],
    source: "SimCity / Spore",
    points: 3,
  },
  {
    category: "Games",
    before: "Peace was never an",
    answer: "option",
    accept: ["option"],
    source: "gaming meme",
    points: 2,
  },
  {
    category: "Games",
    before: "Achievement",
    answer: "unlocked",
    accept: ["unlocked"],
    source: "gaming term",
    points: 2,
  },
  {
    category: "Games",
    before: "Level",
    answer: "up!",
    accept: ["up"],
    source: "gaming term",
    points: 1,
  },
  {
    category: "Games",
    before: "Game",
    answer: "over",
    accept: ["over"],
    source: "arcade classic",
    points: 1,
  },
  {
    category: "Games",
    before: "Would you like to save your",
    answer: "game?",
    accept: ["game"],
    source: "save-point prompt",
    points: 2,
  },
  {
    category: "Games",
    before: "It's on like Donkey",
    answer: "Kong",
    accept: ["kong"],
    source: "gaming catchphrase",
    points: 2,
  },

  // ---- Books (batch 2) ----
  {
    category: "Books",
    before: "It was a pleasure to",
    answer: "burn",
    accept: ["burn"],
    source: "Ray Bradbury — Fahrenheit 451",
    points: 3,
  },
  {
    category: "Books",
    before: "Happy families are all alike; every unhappy family is unhappy in its own",
    answer: "way",
    accept: ["way"],
    source: "Leo Tolstoy — Anna Karenina",
    points: 3,
  },
  {
    category: "Books",
    before: "Mr. and Mrs. Dursley, of number four, Privet Drive, were proud to say that they were perfectly",
    answer: "normal",
    accept: ["normal"],
    source: "J.K. Rowling — Harry Potter and the Philosopher's Stone",
    points: 3,
  },
  {
    category: "Books",
    before: "We're all mad",
    answer: "here",
    accept: ["here"],
    source: "Lewis Carroll — Alice's Adventures in Wonderland",
    points: 2,
  },
  {
    category: "Books",
    before: "Off with their",
    answer: "heads!",
    accept: ["heads"],
    source: "Lewis Carroll — Alice's Adventures in Wonderland",
    points: 2,
  },
  {
    category: "Books",
    before: "Please, sir, I want some",
    answer: "more",
    accept: ["more"],
    source: "Charles Dickens — Oliver Twist",
    points: 2,
  },
  {
    category: "Books",
    before: "Quoth the Raven,",
    answer: "Nevermore",
    accept: ["nevermore"],
    source: "Edgar Allan Poe — The Raven",
    points: 2,
  },
  {
    category: "Books",
    before: "Two roads diverged in a wood, and I— I took the one less traveled",
    answer: "by",
    accept: ["by"],
    source: "Robert Frost — The Road Not Taken",
    points: 3,
  },
  {
    category: "Books",
    before: "Do not go gentle into that good",
    answer: "night",
    accept: ["night"],
    source: "Dylan Thomas — Do Not Go Gentle...",
    points: 2,
  },
  {
    category: "Books",
    before: "Because I could not stop for",
    answer: "Death",
    accept: ["death"],
    source: "Emily Dickinson",
    points: 3,
  },

  // ---- Ads / Slogans (batch 2) ----
  {
    category: "Ads",
    before: "Maybe she's born with it. Maybe it's",
    answer: "Maybelline",
    accept: ["maybelline"],
    source: "Maybelline",
    points: 3,
  },
  {
    category: "Ads",
    before: "The best a man can",
    answer: "get",
    accept: ["get"],
    source: "Gillette",
    points: 2,
  },
  {
    category: "Ads",
    before: "Don't leave home without",
    answer: "it",
    accept: ["it"],
    source: "American Express",
    points: 3,
  },
  {
    category: "Ads",
    before: "Where's the",
    answer: "beef?",
    accept: ["beef"],
    source: "Wendy's",
    points: 2,
  },
  {
    category: "Ads",
    before: "Save money. Live",
    answer: "better",
    accept: ["better"],
    source: "Walmart",
    points: 3,
  },
  {
    category: "Ads",
    before: "Plop plop, fizz fizz, oh what a relief it",
    answer: "is",
    accept: ["is"],
    source: "Alka-Seltzer",
    points: 3,
  },
  {
    category: "Ads",
    before: "Gimme a break, gimme a break, break me off a piece of that",
    answer: "Kit Kat bar",
    accept: ["kit kat bar", "kit kat", "kitkat bar", "kitkat"],
    source: "Kit Kat",
    points: 3,
  },
  {
    category: "Ads",
    before: "I'd like to buy the world a",
    answer: "Coke",
    accept: ["coke", "coca cola"],
    source: "Coca-Cola",
    points: 3,
  },

  // ---- Speeches (historical & famous) ----
  {
    category: "Speeches",
    before: "I have a",
    answer: "dream",
    accept: ["dream"],
    source: "Martin Luther King Jr.",
    points: 1,
  },
  {
    category: "Speeches",
    before: "Ask not what your country can do for you — ask what you can do for your",
    answer: "country",
    accept: ["country"],
    source: "John F. Kennedy, Inaugural Address",
    points: 2,
  },
  {
    category: "Speeches",
    before: "Four score and seven years",
    answer: "ago",
    accept: ["ago"],
    source: "Abraham Lincoln, Gettysburg Address",
    points: 2,
  },
  {
    category: "Speeches",
    before: "That's one small step for man, one giant leap for",
    answer: "mankind",
    accept: ["mankind"],
    source: "Neil Armstrong",
    points: 2,
  },
  {
    category: "Speeches",
    before: "We shall fight on the",
    answer: "beaches",
    accept: ["beaches"],
    source: "Winston Churchill",
    points: 3,
  },
  {
    category: "Speeches",
    before: "The only thing we have to fear is fear",
    answer: "itself",
    accept: ["itself"],
    source: "Franklin D. Roosevelt",
    points: 2,
  },
  {
    category: "Speeches",
    before: "I am not a",
    answer: "crook",
    accept: ["crook"],
    source: "Richard Nixon",
    points: 3,
  },
  {
    category: "Speeches",
    before: "Mr. Gorbachev, tear down this",
    answer: "wall!",
    accept: ["wall"],
    source: "Ronald Reagan",
    points: 2,
  },
  {
    category: "Speeches",
    before: "...government of the people, by the people, for the",
    answer: "people",
    accept: ["people"],
    source: "Abraham Lincoln, Gettysburg Address",
    points: 2,
  },
  {
    category: "Speeches",
    before: "Speak softly and carry a big",
    answer: "stick",
    accept: ["stick"],
    source: "Theodore Roosevelt",
    points: 3,
  },
  {
    category: "Speeches",
    before: "I came, I saw, I",
    answer: "conquered",
    accept: ["conquered"],
    source: "Julius Caesar",
    points: 2,
  },
  {
    category: "Speeches",
    before: "Give me liberty, or give me",
    answer: "death!",
    accept: ["death"],
    source: "Patrick Henry",
    points: 2,
  },
  {
    category: "Speeches",
    before: "Et tu,",
    answer: "Brute?",
    accept: ["brute", "brutus"],
    source: "Shakespeare — Julius Caesar",
    points: 2,
  },
  {
    category: "Speeches",
    before: "Yes we",
    answer: "can!",
    accept: ["can"],
    source: "Barack Obama",
    points: 2,
  },
  {
    category: "Speeches",
    before: "The buck stops",
    answer: "here",
    accept: ["here"],
    source: "Harry S. Truman",
    points: 3,
  },
];

// Expose for the browser (no modules, so it just works from file://).
if (typeof window !== "undefined") {
  window.QUOTE_DECK = QUOTE_DECK;
}
