/*
 * Quote deck for "Finish the Line" — the pop-culture quote board game.
 *
 * Each entry:
 *   category  – used for the category filter and tile colour
 *   before    – the prompt shown to the player (the setup of the quote)
 *   answer    – the canonical completion (shown on reveal)
 *   accept    – array of accepted answers, all lowercased & punctuation-light.
 *               The player's guess is normalised the same way before matching,
 *               so "full of stars" matches "Full of stars!".
 *   source    – where it's from (shown after the round)
 *   points    – how many spaces a correct answer moves you (harder = more)
 */
const QUOTE_DECK = [
  // ---- Movies ----
  {
    category: "Movies",
    before: "Oh my God, it's",
    answer: "full of stars",
    accept: ["full of stars"],
    source: "2001: A Space Odyssey (2010 line)",
    points: 3,
  },
  {
    category: "Movies",
    before: "Here's looking at you,",
    answer: "kid",
    accept: ["kid"],
    source: "Casablanca",
    points: 1,
  },
  {
    category: "Movies",
    before: "May the Force be",
    answer: "with you",
    accept: ["with you"],
    source: "Star Wars",
    points: 1,
  },
  {
    category: "Movies",
    before: "I'm going to make him an offer he",
    answer: "can't refuse",
    accept: ["can't refuse", "cannot refuse"],
    source: "The Godfather",
    points: 2,
  },
  {
    category: "Movies",
    before: "You're gonna need a bigger",
    answer: "boat",
    accept: ["boat"],
    source: "Jaws",
    points: 1,
  },
  {
    category: "Movies",
    before: "Life is like a box of",
    answer: "chocolates",
    accept: ["chocolates", "chocolate"],
    source: "Forrest Gump",
    points: 1,
  },
  {
    category: "Movies",
    before: "Frankly, my dear, I don't give a",
    answer: "damn",
    accept: ["damn"],
    source: "Gone with the Wind",
    points: 2,
  },
  {
    category: "Movies",
    before: "Say hello to my little",
    answer: "friend",
    accept: ["friend"],
    source: "Scarface",
    points: 1,
  },
  {
    category: "Movies",
    before: "Why so",
    answer: "serious?",
    accept: ["serious"],
    source: "The Dark Knight",
    points: 2,
  },
  {
    category: "Movies",
    before: "You had me at",
    answer: "hello",
    accept: ["hello"],
    source: "Jerry Maguire",
    points: 2,
  },
  {
    category: "Movies",
    before: "To infinity and",
    answer: "beyond",
    accept: ["beyond"],
    source: "Toy Story",
    points: 1,
  },
  {
    category: "Movies",
    before: "I'll be",
    answer: "back",
    accept: ["back"],
    source: "The Terminator",
    points: 1,
  },
  {
    category: "Movies",
    before: "There's no place like",
    answer: "home",
    accept: ["home"],
    source: "The Wizard of Oz",
    points: 1,
  },
  {
    category: "Movies",
    before: "Just keep",
    answer: "swimming",
    accept: ["swimming"],
    source: "Finding Nemo",
    points: 1,
  },

  // ---- TV ----
  {
    category: "TV",
    before: "How you",
    answer: "doin'?",
    accept: ["doin", "doing", "doin'"],
    source: "Friends (Joey)",
    points: 2,
  },
  {
    category: "TV",
    before: "Winter is",
    answer: "coming",
    accept: ["coming"],
    source: "Game of Thrones",
    points: 1,
  },
  {
    category: "TV",
    before: "I am the one who",
    answer: "knocks",
    accept: ["knocks"],
    source: "Breaking Bad",
    points: 2,
  },
  {
    category: "TV",
    before: "That's what",
    answer: "she said",
    accept: ["she said"],
    source: "The Office (Michael Scott)",
    points: 2,
  },
  {
    category: "TV",
    before: "Legen — wait for it —",
    answer: "dary",
    accept: ["dary", "legendary"],
    source: "How I Met Your Mother (Barney)",
    points: 2,
  },
  {
    category: "TV",
    before: "Live long and",
    answer: "prosper",
    accept: ["prosper"],
    source: "Star Trek",
    points: 1,
  },
  {
    category: "TV",
    before: "Yada yada",
    answer: "yada",
    accept: ["yada"],
    source: "Seinfeld",
    points: 2,
  },

  // ---- Music ----
  {
    category: "Music",
    before: "Is this the real life? Is this just",
    answer: "fantasy?",
    accept: ["fantasy"],
    source: "Queen — Bohemian Rhapsody",
    points: 2,
  },
  {
    category: "Music",
    before: "'Cause baby, you're a",
    answer: "firework",
    accept: ["firework", "fire work"],
    source: "Katy Perry — Firework",
    points: 2,
  },
  {
    category: "Music",
    before: "We don't need no",
    answer: "education",
    accept: ["education"],
    source: "Pink Floyd — Another Brick in the Wall",
    points: 2,
  },
  {
    category: "Music",
    before: "I want it",
    answer: "that way",
    accept: ["that way"],
    source: "Backstreet Boys — I Want It That Way",
    points: 2,
  },
  {
    category: "Music",
    before: "Hello from the",
    answer: "other side",
    accept: ["other side", "otherside"],
    source: "Adele — Hello",
    points: 2,
  },
  {
    category: "Music",
    before: "Sweet dreams are made of",
    answer: "this",
    accept: ["this", "these"],
    source: "Eurythmics — Sweet Dreams",
    points: 2,
  },
  {
    category: "Music",
    before: "Never gonna give you",
    answer: "up",
    accept: ["up"],
    source: "Rick Astley — Never Gonna Give You Up",
    points: 1,
  },

  // ---- Internet / Memes ----
  {
    category: "Internet",
    before: "All your base are belong to",
    answer: "us",
    accept: ["us"],
    source: "Zero Wing (meme)",
    points: 3,
  },
  {
    category: "Internet",
    before: "One does not simply walk into",
    answer: "Mordor",
    accept: ["mordor"],
    source: "LOTR / meme",
    points: 2,
  },
  {
    category: "Internet",
    before: "It's over 9",
    answer: "000!",
    accept: ["000", "9000", "thousand"],
    source: "Dragon Ball Z (meme)",
    points: 2,
  },
  {
    category: "Internet",
    before: "But that's none of my",
    answer: "business",
    accept: ["business"],
    source: "Kermit / meme",
    points: 2,
  },
  {
    category: "Internet",
    before: "I can haz",
    answer: "cheezburger?",
    accept: ["cheezburger", "cheeseburger", "cheezburger?"],
    source: "LOLcats",
    points: 2,
  },

  // ---- Games ----
  {
    category: "Games",
    before: "The cake is a",
    answer: "lie",
    accept: ["lie"],
    source: "Portal",
    points: 2,
  },
  {
    category: "Games",
    before: "It's dangerous to go alone! Take",
    answer: "this",
    accept: ["this", "this."],
    source: "The Legend of Zelda",
    points: 2,
  },
  {
    category: "Games",
    before: "War. War never",
    answer: "changes",
    accept: ["changes"],
    source: "Fallout",
    points: 2,
  },
  {
    category: "Games",
    before: "A man chooses, a slave",
    answer: "obeys",
    accept: ["obeys"],
    source: "BioShock",
    points: 3,
  },
  {
    category: "Games",
    before: "Do a",
    answer: "barrel roll!",
    accept: ["barrel roll", "barrel roll!"],
    source: "Star Fox 64",
    points: 2,
  },

  // ---- Movies (expansion) ----
  {
    category: "Movies",
    before: "I see dead",
    answer: "people",
    accept: ["people"],
    source: "The Sixth Sense",
    points: 2,
  },
  {
    category: "Movies",
    before: "You can't handle the",
    answer: "truth!",
    accept: ["truth"],
    source: "A Few Good Men",
    points: 2,
  },
  {
    category: "Movies",
    before: "Houston, we have a",
    answer: "problem",
    accept: ["problem"],
    source: "Apollo 13",
    points: 1,
  },
  {
    category: "Movies",
    before: "Elementary, my dear",
    answer: "Watson",
    accept: ["watson"],
    source: "Sherlock Holmes",
    points: 2,
  },
  {
    category: "Movies",
    before: "I feel the need — the need for",
    answer: "speed",
    accept: ["speed", "for speed"],
    source: "Top Gun",
    points: 2,
  },
  {
    category: "Movies",
    before: "Nobody puts Baby in a",
    answer: "corner",
    accept: ["corner"],
    source: "Dirty Dancing",
    points: 2,
  },
  {
    category: "Movies",
    before: "They may take our lives, but they'll never take our",
    answer: "freedom!",
    accept: ["freedom"],
    source: "Braveheart",
    points: 3,
  },
  {
    category: "Movies",
    before: "Keep your friends close, but your enemies",
    answer: "closer",
    accept: ["closer", "even closer"],
    source: "The Godfather Part II",
    points: 2,
  },
  {
    category: "Movies",
    before: "You talkin' to",
    answer: "me?",
    accept: ["me"],
    source: "Taxi Driver",
    points: 2,
  },
  {
    category: "Movies",
    before: "Hasta la vista,",
    answer: "baby",
    accept: ["baby"],
    source: "Terminator 2: Judgment Day",
    points: 2,
  },
  {
    category: "Movies",
    before: "Roads? Where we're going, we don't need",
    answer: "roads",
    accept: ["roads"],
    source: "Back to the Future",
    points: 2,
  },
  {
    category: "Movies",
    before: "With great power comes great",
    answer: "responsibility",
    accept: ["responsibility"],
    source: "Spider-Man",
    points: 1,
  },
  {
    category: "Movies",
    before: "No, I am your",
    answer: "father",
    accept: ["father"],
    source: "The Empire Strikes Back",
    points: 1,
  },
  {
    category: "Movies",
    before: "Do. Or do not. There is no",
    answer: "try",
    accept: ["try"],
    source: "The Empire Strikes Back (Yoda)",
    points: 2,
  },
  {
    category: "Movies",
    before: "Toto, I've a feeling we're not in Kansas",
    answer: "anymore",
    accept: ["anymore", "any more"],
    source: "The Wizard of Oz",
    points: 2,
  },
  {
    category: "Movies",
    before: "You shall not",
    answer: "pass!",
    accept: ["pass"],
    source: "The Lord of the Rings (Gandalf)",
    points: 2,
  },
  {
    category: "Movies",
    before: "Wax on, wax",
    answer: "off",
    accept: ["off"],
    source: "The Karate Kid",
    points: 2,
  },
  {
    category: "Movies",
    before: "E.T. phone",
    answer: "home",
    accept: ["home"],
    source: "E.T. the Extra-Terrestrial",
    points: 1,
  },
  {
    category: "Movies",
    before: "I'm the king of the",
    answer: "world!",
    accept: ["world"],
    source: "Titanic",
    points: 2,
  },
  {
    category: "Movies",
    before: "Show me the",
    answer: "money!",
    accept: ["money"],
    source: "Jerry Maguire",
    points: 2,
  },
  {
    category: "Movies",
    before: "Round up the usual",
    answer: "suspects",
    accept: ["suspects"],
    source: "Casablanca",
    points: 2,
  },
  {
    category: "Movies",
    before: "Carpe diem. Seize the",
    answer: "day",
    accept: ["day", "day boys", "day, boys"],
    source: "Dead Poets Society",
    points: 2,
  },
  {
    category: "Movies",
    before: "The first rule of Fight Club is: you do not talk about",
    answer: "Fight Club",
    accept: ["fight club"],
    source: "Fight Club",
    points: 2,
  },
  {
    category: "Movies",
    before: "Life finds a",
    answer: "way",
    accept: ["way"],
    source: "Jurassic Park",
    points: 2,
  },

  // ---- TV (expansion) ----
  {
    category: "TV",
    before: "Have you tried turning it off and on",
    answer: "again?",
    accept: ["again"],
    source: "The IT Crowd",
    points: 2,
  },
  {
    category: "TV",
    before: "Suit",
    answer: "up!",
    accept: ["up"],
    source: "How I Met Your Mother (Barney)",
    points: 2,
  },
  {
    category: "TV",
    before: "The truth is out",
    answer: "there",
    accept: ["there"],
    source: "The X-Files",
    points: 2,
  },
  {
    category: "TV",
    before: "Resistance is",
    answer: "futile",
    accept: ["futile"],
    source: "Star Trek: The Next Generation (Borg)",
    points: 2,
  },
  {
    category: "TV",
    before: "Space: the final",
    answer: "frontier",
    accept: ["frontier"],
    source: "Star Trek",
    points: 1,
  },
  {
    category: "TV",
    before: "Make it",
    answer: "so",
    accept: ["so"],
    source: "Star Trek: TNG (Picard)",
    points: 2,
  },
  {
    category: "TV",
    before: "I've made a huge",
    answer: "mistake",
    accept: ["mistake"],
    source: "Arrested Development",
    points: 3,
  },
  {
    category: "TV",
    before: "No soup for",
    answer: "you!",
    accept: ["you"],
    source: "Seinfeld (Soup Nazi)",
    points: 2,
  },
  {
    category: "TV",
    before: "Survey",
    answer: "says!",
    accept: ["says"],
    source: "Family Feud",
    points: 2,
  },
  {
    category: "TV",
    before: "Book 'em,",
    answer: "Danno",
    accept: ["danno"],
    source: "Hawaii Five-O",
    points: 3,
  },
  {
    category: "TV",
    before: "And that's the way it",
    answer: "is",
    accept: ["is"],
    source: "CBS Evening News (Walter Cronkite)",
    points: 3,
  },
  {
    category: "TV",
    before: "You are the weakest link,",
    answer: "goodbye",
    accept: ["goodbye", "good bye"],
    source: "The Weakest Link",
    points: 2,
  },
  {
    category: "TV",
    before: "Danger, Will",
    answer: "Robinson!",
    accept: ["robinson"],
    source: "Lost in Space",
    points: 3,
  },
  {
    category: "TV",
    before: "Whatchu talkin' 'bout,",
    answer: "Willis?",
    accept: ["willis"],
    source: "Diff'rent Strokes",
    points: 3,
  },
  {
    category: "TV",
    before: "Marcia, Marcia,",
    answer: "Marcia!",
    accept: ["marcia"],
    source: "The Brady Bunch",
    points: 3,
  },
  {
    category: "TV",
    before: "Clear eyes, full hearts,",
    answer: "can't lose",
    accept: ["can't lose", "cant lose"],
    source: "Friday Night Lights",
    points: 3,
  },
  {
    category: "TV",
    before: "Say my",
    answer: "name",
    accept: ["name"],
    source: "Breaking Bad",
    points: 2,
  },

  // ---- Music (expansion) ----
  {
    category: "Music",
    before: "Don't stop",
    answer: "believin'",
    accept: ["believin", "believing"],
    source: "Journey — Don't Stop Believin'",
    points: 1,
  },
  {
    category: "Music",
    before: "We will, we will",
    answer: "rock you",
    accept: ["rock you"],
    source: "Queen — We Will Rock You",
    points: 1,
  },
  {
    category: "Music",
    before: "And I will always love",
    answer: "you",
    accept: ["you"],
    source: "Whitney Houston — I Will Always Love You",
    points: 1,
  },
  {
    category: "Music",
    before: "Girls just wanna have",
    answer: "fun",
    accept: ["fun"],
    source: "Cyndi Lauper — Girls Just Want to Have Fun",
    points: 1,
  },
  {
    category: "Music",
    before: "Billie Jean is not my",
    answer: "lover",
    accept: ["lover"],
    source: "Michael Jackson — Billie Jean",
    points: 2,
  },
  {
    category: "Music",
    before: "Take on",
    answer: "me",
    accept: ["me"],
    source: "a-ha — Take On Me",
    points: 2,
  },
  {
    category: "Music",
    before: "Should I stay or should I",
    answer: "go",
    accept: ["go", "go now"],
    source: "The Clash — Should I Stay or Should I Go",
    points: 2,
  },
  {
    category: "Music",
    before: "Another one bites the",
    answer: "dust",
    accept: ["dust"],
    source: "Queen — Another One Bites the Dust",
    points: 1,
  },
  {
    category: "Music",
    before: "I'm on the highway to",
    answer: "hell",
    accept: ["hell"],
    source: "AC/DC — Highway to Hell",
    points: 2,
  },
  {
    category: "Music",
    before: "Whoa, we're halfway there — livin' on a",
    answer: "prayer",
    accept: ["prayer"],
    source: "Bon Jovi — Livin' on a Prayer",
    points: 2,
  },
  {
    category: "Music",
    before: "Every breath you",
    answer: "take",
    accept: ["take"],
    source: "The Police — Every Breath You Take",
    points: 2,
  },
  {
    category: "Music",
    before: "Players gonna play — I just shake it",
    answer: "off",
    accept: ["off"],
    source: "Taylor Swift — Shake It Off",
    points: 1,
  },
  {
    category: "Music",
    before: "Oops!... I did it",
    answer: "again",
    accept: ["again"],
    source: "Britney Spears — Oops!... I Did It Again",
    points: 1,
  },
  {
    category: "Music",
    before: "Hit me baby one more",
    answer: "time",
    accept: ["time"],
    source: "Britney Spears — ...Baby One More Time",
    points: 2,
  },
  {
    category: "Music",
    before: "Clap along if you feel like a room without a",
    answer: "roof",
    accept: ["roof"],
    source: "Pharrell Williams — Happy",
    points: 3,
  },
  {
    category: "Music",
    before: "Somebody once told me the world is gonna roll",
    answer: "me",
    accept: ["me"],
    source: "Smash Mouth — All Star",
    points: 3,
  },
  {
    category: "Music",
    before: "I gotta feeling that tonight's gonna be a good",
    answer: "night",
    accept: ["night"],
    source: "The Black Eyed Peas — I Gotta Feeling",
    points: 2,
  },
  {
    category: "Music",
    before: "You may say I'm a dreamer, but I'm not the only",
    answer: "one",
    accept: ["one"],
    source: "John Lennon — Imagine",
    points: 2,
  },

  // ---- Internet / Memes (expansion) ----
  {
    category: "Internet",
    before: "This is",
    answer: "Sparta!",
    accept: ["sparta"],
    source: "300 (meme)",
    points: 2,
  },
  {
    category: "Internet",
    before: "Ain't nobody got time for",
    answer: "that",
    accept: ["that"],
    source: "viral news clip (meme)",
    points: 2,
  },
  {
    category: "Internet",
    before: "Shut up and take my",
    answer: "money!",
    accept: ["money"],
    source: "Futurama (meme)",
    points: 2,
  },
  {
    category: "Internet",
    before: "Release the",
    answer: "Kraken!",
    accept: ["kraken"],
    source: "Clash of the Titans (meme)",
    points: 2,
  },
  {
    category: "Internet",
    before: "Keep calm and carry",
    answer: "on",
    accept: ["on"],
    source: "wartime poster (meme)",
    points: 1,
  },
  {
    category: "Internet",
    before: "Well, that escalated",
    answer: "quickly",
    accept: ["quickly"],
    source: "Anchorman (meme)",
    points: 2,
  },
  {
    category: "Internet",
    before: "The floor is",
    answer: "lava",
    accept: ["lava"],
    source: "childhood game (meme)",
    points: 2,
  },
  {
    category: "Internet",
    before: "Pics or it didn't",
    answer: "happen",
    accept: ["happen"],
    source: "internet saying",
    points: 2,
  },
  {
    category: "Internet",
    before: "Do you want ants? Because that's how you get",
    answer: "ants",
    accept: ["ants"],
    source: "Archer (meme)",
    points: 3,
  },
  {
    category: "Internet",
    before: "Do you even",
    answer: "lift?",
    accept: ["lift"],
    source: "gym meme",
    points: 2,
  },
  {
    category: "Internet",
    before: "Leeroy",
    answer: "Jenkins!",
    accept: ["jenkins"],
    source: "World of Warcraft (meme)",
    points: 3,
  },
  {
    category: "Internet",
    before: "Por que no los",
    answer: "dos?",
    accept: ["dos", "two", "both"],
    source: "Old El Paso ad — \"why not both?\" (meme)",
    points: 3,
  },

  // ---- Games (expansion) ----
  {
    category: "Games",
    before: "Finish",
    answer: "him!",
    accept: ["him"],
    source: "Mortal Kombat",
    points: 2,
  },
  {
    category: "Games",
    before: "Thank you Mario! But our princess is in another",
    answer: "castle!",
    accept: ["castle"],
    source: "Super Mario Bros.",
    points: 3,
  },
  {
    category: "Games",
    before: "It's-a me,",
    answer: "Mario!",
    accept: ["mario"],
    source: "Super Mario 64",
    points: 1,
  },
  {
    category: "Games",
    before: "Get over",
    answer: "here!",
    accept: ["here"],
    source: "Mortal Kombat (Scorpion)",
    points: 2,
  },
  {
    category: "Games",
    before: "Stay a while and",
    answer: "listen",
    accept: ["listen"],
    source: "Diablo (Deckard Cain)",
    points: 3,
  },
  {
    category: "Games",
    before: "You must construct additional",
    answer: "pylons",
    accept: ["pylons"],
    source: "StarCraft",
    points: 3,
  },
  {
    category: "Games",
    before: "Nothing is true; everything is",
    answer: "permitted",
    accept: ["permitted"],
    source: "Assassin's Creed",
    points: 3,
  },
  {
    category: "Games",
    before: "Praise the",
    answer: "sun!",
    accept: ["sun"],
    source: "Dark Souls",
    points: 3,
  },
  {
    category: "Games",
    before: "Fus Ro",
    answer: "Dah!",
    accept: ["dah"],
    source: "The Elder Scrolls V: Skyrim",
    points: 3,
  },
  {
    category: "Games",
    before: "I used to be an adventurer like you, then I took an arrow to the",
    answer: "knee",
    accept: ["knee"],
    source: "The Elder Scrolls V: Skyrim",
    points: 3,
  },
];

// Expose for the browser (no modules, so it just works from file://).
if (typeof window !== "undefined") {
  window.QUOTE_DECK = QUOTE_DECK;
}
